### ISSUE TITLE
ClearLagg kills repeating tasks when performing gc/stops

### ISSUE THREAD

**Issue by AryToNeX** [Jikoo/EnchantableBlocks#1]
I have the latest release of this plugin (when it was called EnchantedFurnace) and it seems ClearLagg makes it stop whenever it garbage collects or halts the server (ex. on low TPS trying to reduce lag).

Nothing worth mentioning on the server log, it just happens.

Also, doesn't this plugin need a 1.13 compatibility upgrade?

**Comment by Jikoo** [comment]
On my list, just a little lower due to needing to figure out what I'm doing with it. Probably going to drop backwards compatibility.
It should work to some degree out of the box. ClearLagg is likely killing tasks, which EnchantedFurnace uses a decent amount of.

**Comment by Jikoo** [comment]
Re: ClearLagg - I'll make sure the ticking runnable is restarted whenever it's detected to be killed. Should have some progress made today.

**Comment by Jikoo** [comment]
With dropping support for older versions, EnchantableBlocks no longer uses repeating tasks.
