### ISSUE TITLE
Furnace duplication

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#12]
Hi,

With the last version from my previous issue https://github.com/Jikoo/EnchantableBlocks/issues/11#issuecomment-703269533 and Paper 1.16.3 when you break an enchanted furnace with or without items inside, a classic furnace duplicates and drops with the rest.

**Comment by SmallSansSerif** [comment]
Subscribing here as I also use Paper and want to use latest.

**Comment by Jikoo** [comment]
Try the [latest build](https://ci.appveyor.com/project/Jikoo/enchantableblocks/build/artifacts) please.

**Comment by aurel85** [comment]
Everything is ok with this version, thank you !
