### ISSUE TITLE
McMMO and fortune enchant

### ISSUE THREAD

**Issue by jordanwilliams1** [Jikoo/EnchantableBlocks#17]
Had a report that fortune enchant doesn't work on the furance because mcmmo double smelt over rides it?

quote from a ticket via my support

im glad someone else brought this up actually bc i was doing something similar the other day and got slightly confused
i was smelting coal ore with an ulti furnace which also has the fortune enchant
and i got double the amount of ore i smelted but i was expecting more from the fortune since i usually get double from mcmmo anyway

**Comment by Jikoo** [comment]
What does "ulti furnace" mean? I'll look at mcMMO, but if it's not just EB/mcMMO in play I need to know in case there's something else.
