### ISSUE TITLE
Enchantment displayed in the enchanting table

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#38]
Hi,

The name proposed by the enchanting table when you try to enchant an oven is not at all the one you will have next, the proof in picture.

I use the last version of this plugin (3.0.0) and Paper 1.17.1.

![2021-08-04_21_57_14 png 113ac1bbb3f67323eabdbac4d4fae004](https://user-images.githubusercontent.com/24486147/128250035-0e9b73e1-3647-4ac9-b4d2-a85ab572c55f.png)

![2021-08-04_21_57_26 png 4cfa8bd571bb27d30a9f5c145721a517](https://user-images.githubusercontent.com/24486147/128250048-809117e8-8a2b-4aef-86bc-0b70cdab4e41.png)

Thank you in advance.

**Comment by Jikoo** [comment]
Looks like the mapping for registry IDs has changed so it's falling through to the default of ID 0.

**Comment by aurel85** [comment]
Everything is ok thank you !
