### ISSUE TITLE
2.0.2-SNAPSHOT doesn't work on 1.14

### ISSUE THREAD

**Issue by justablob** [Jikoo/EnchantableBlocks#4]
I've compiled 2.0.2-SNAPSHOT and i've shaded lang3, the plugin loads and all, but i can't use the enchanting table to enchant a furnace, and when combining a furnace with a book in the anvil, it doesn't do anything, even though the furnace has the enchantment. Items always take 10s to process. Spigot version: git-Spigot-1eece4f-8879c31.

**Comment by Jikoo** [comment]
From which commit? If you read the last commit, you'll note the part where it says "currently nonfunctional." If all you want is shaded lang3, you should be compiling from dfa8669.
