### ISSUE TITLE
Infinite experience - grindstone

### ISSUE THREAD

**Issue by Aides123** [Jikoo/EnchantableBlocks#50]
Hey, players can take a enchants off a furnace by grindstone and have infinite experience from it.
Can you block grindstone?

**Comment by Jikoo** [comment]
What do you mean? Using a grindstone functions just as it does in vanilla - enchantments are removed and a value of experience based on the enchantments returned is given. Unless your enchantment settings are insanely overpowered, there's no way the amount of exp refunded for grinding enchantments off can ever exceed the cost of performing an enchantment.

Going to need more detail to help you, exact reproduction steps would help. Maybe also post your config and other relevant details, like server and EB version. If you're running a grindstone modification, you should raise an issue with the maintainer of that if they aren't supporting other enchanted objects.

**Comment by Jikoo** [comment]
Closing due to lack of response.
