### ISSUE TITLE
This plugin does not work in PaperSpigot 1.14.2

### ISSUE THREAD

**Issue by AryToNeX** [Jikoo/EnchantableBlocks#6]
I tested this plugin in a clean PaperSpigot environment and I saw that enchanting furnaces in a table is impossible. Maybe the event is force canceled? I think so because the three enchantment proposals appear just for one tick.

Using PS #96 on 1.14.2

**Comment by Jikoo** [comment]
This is a Spigot bug, doesn't respect enchantment offer changes unless the item is inserted via shift click.
