### ISSUE TITLE
Silk Touch and cooking tools

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#9]
Hi,

Finally everything is not ok with 2.0.4 : when cooking iron or gold tools with coal (or other) is used 1 coal for 1 item.

I use PaperSpigot 1.14.4.

**Comment by Jikoo** [comment]
Yes, I did not address Silk Touch issues yet. I suspect that Spigot is now decrementing the fuel even if the event is cancelled.
